CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: '/content/output'
WORKERS: 2
PRINT_FREQ: 100

TRAIN:
  IMAGE_SIZE:
  - 256
  - 256
  BASE_SIZE: 32
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 10
  RESUME: true
  OPTIMIZER: adam
  LR: 0.0001
  WD: 0.0001
  MOMENTUM: 0.9  
TEST:
  IMAGE_SIZE:
  - 256
  - 256
  BASE_SIZE: 32
